### PR TITLE
Fixing my link - Solving Issue

### PR DESCRIPTION
**Pull request by katherynisabell**

### CODE REVIEW

**Comment by katherynisabell** [comment]
Link to issue https://github.com/barrycumbie/fuzzy-chainsaw-november/issues/28#issue-1568855207

**Comment by katherynisabell** [comment]
Closes #28

**Comment by katherynisabell** [comment]
resolves #28

**Comment by barrycumbie** [comment]
Need to add into the FIRST comment of this Pull Request (PR)

> closes #XYZ

where XYZ = the same number of your issue

This will `bind` this PR with the Issue and show up on the ➡️ menu under 'Development'

Yes, PR. Anything else to improve the APP?

**Pull request merged**
